version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tket_postgres
    restart: always
    environment:
      POSTGRES_USER: tket_admin
      POSTGRES_PASSWORD: tket_db_password1234
      POSTGRES_DB: tket_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    container_name: tket_redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: tket_django
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis

volumes:
  postgres_data: