-- -- ==========================================
-- ANALYTICAL QUERIES
-- -- ==========================================


-- QUERY 1: Find Users Without Reservations
    -- Description: Retrieves the first and last names of all 'Spectator' 
    -- accounts that do not have any records in the reservations table.

SELECT first_name, last_name 
FROM users 
WHERE user_id NOT IN (SELECT user_id FROM reservations) 
AND role = 'Spectator';

-- QUERY 2: Find Users With At Least One Reservation
    -- Description: Retrieves the first and last names of all 'Spectator' 
    -- accounts that exist in the reservations table. Using IN prevents 
    -- duplicate names for users with multiple reservations.

SELECT first_name, last_name 
FROM users 
WHERE user_id IN (SELECT user_id FROM reservations) 
AND role = 'Spectator';

-- QUERY 3: Total Payments by User Per Month
    -- Description: Calculates the total revenue generated by each user, 
    -- grouped by month and year. Only includes 'Success' transactions.

SELECT u.username,
    TO_CHAR(p.paid_at, 'YYYY-MM') AS payment_month,
    SUM(p.amount) AS total_paid
FROM users u
JOIN reservations r ON u.user_id = r.user_id
JOIN payments p ON r.reservation_id = p.reservation_id
WHERE p.transaction_status = 'Success'
GROUP BY u.username, TO_CHAR(p.paid_at, 'YYYY-MM');

