-- ==========================================
-- ANALYTICAL QUERIES
-- ==========================================


-- QUERY 1: Find Users Without Reservations
    -- Retrieves the first and last names of all 'Spectator'
    -- accounts that do not have any records in the
    -- reservations table.

SELECT first_name, last_name 
FROM users 
WHERE user_id NOT IN (SELECT user_id FROM reservations) 
AND role = 'Spectator';

-- QUERY 2: Find Users With At Least One Reservation
    -- Retrieves the first and last names of all 'Spectator'
    -- accounts that exist in the reservations table. Using IN
    -- prevents duplicate names for users with multiple reservations.

SELECT first_name, last_name 
FROM users 
WHERE user_id IN (SELECT user_id FROM reservations) 
AND role = 'Spectator';

-- QUERY 3: Total Payments by User Per Month
    -- Calculates the total revenue generated by each user, grouped
    -- by month and year. Only includes 'Success' transactions.

SELECT u.username,
    TO_CHAR(p.paid_at, 'YYYY-MM') AS payment_month,
    SUM(p.amount) AS total_paid
FROM users u
JOIN reservations r ON u.user_id = r.user_id
JOIN payments p ON r.reservation_id = p.reservation_id
WHERE p.transaction_status = 'Success'
GROUP BY u.username, TO_CHAR(p.paid_at, 'YYYY-MM');

-- QUERY 4: Users With Only One Purchase Per City
    -- Retrieves usernames of users who have never purchased more
    -- than one ticket in any single city.

SELECT username 
FROM users 
WHERE user_id NOT IN (
    SELECT r.user_id 
    FROM reservations r
    JOIN tickets t ON r.ticket_id = t.ticket_id
    WHERE r.reservation_status = 'Confirmed'
    GROUP BY r.user_id, t.venue_city
    HAVING COUNT(*) > 1
)
AND user_id IN (SELECT user_id FROM reservations);

-- QUERY 5: User With The Most Recent Reservation
    -- Retrieves the username of the user who made the most recent
    -- purchase, ordered by the reservation timestamp.

SELECT u.username 
FROM users u 
JOIN reservations r ON u.user_id = r.user_id 
ORDER BY r.reserved_at DESC 
LIMIT 1;

-- QUERY 6: Users Spending Above the Global Average
    -- Uses COALESCE to return either the email or phone number 
    -- (prioritizing email) for users whose total successful payment
    -- amount strictly exceeds the average total spent per paying user.

SELECT 
    u.username,
    COALESCE(u.email, u.phone_number) AS contact_info
FROM users u
JOIN reservations r ON u.user_id = r.user_id
JOIN payments p ON r.reservation_id = p.reservation_id
WHERE p.transaction_status = 'Success'
GROUP BY u.user_id, u.username, u.email, u.phone_number
HAVING SUM(p.amount) > (
    SELECT AVG(user_total) 
    FROM (
        SELECT SUM(p2.amount) AS user_total
        FROM reservations r2
        JOIN payments p2 ON r2.reservation_id = p2.reservation_id
        WHERE p2.transaction_status = 'Success'
        GROUP BY r2.user_id
    ) subquery
);

-- QUERY 7: Total Tickets Sold per Sport Type
    -- Calculates the total sum of ticket quantities from confirmed 
    -- reservations, grouped by the sport type of the match.

SELECT 
    t.sport_type, 
    SUM(r.quantity) AS total_tickets_sold
FROM tickets t
JOIN reservations r ON t.ticket_id = r.ticket_id
WHERE r.reservation_status = 'Confirmed'
GROUP BY t.sport_type;

-- QUERY 8: Top 3 Users by Ticket Volume in the Last Week
    -- Retrieves the usernames and total tickets purchased for the top 
    -- 3 users who bought the most tickets within the last 7 days.

SELECT u.username, SUM(r.quantity) AS total_tickets
FROM users u
JOIN reservations r ON u.user_id = r.user_id
WHERE r.reserved_at >= CURRENT_TIMESTAMP - INTERVAL '7 days'
AND r.reservation_status = 'Confirmed'
GROUP BY u.user_id, u.username
ORDER BY total_tickets DESC
LIMIT 3;

-- QUERY 9: Tickets Sold in the USA(replaced Tehran) by City
    -- Retrieves the total number of confirmed tickets sold specifically 
    -- in USA cities, grouped by each city to simulate regional filtering.

SELECT 
    t.venue_city, 
    SUM(r.quantity) AS total_tickets_sold
FROM tickets t
JOIN reservations r ON t.ticket_id = r.ticket_id
WHERE r.reservation_status = 'Confirmed' 
  AND t.venue_city IN ('Los Angeles', 'Miami', 'Chicago', 'San Francisco', 'Phoenix', 'Boston')
GROUP BY t.venue_city;

-- QUERY 10: Cities Where the Oldest User Made Purchases
    -- Retrieves a unique list of cities where the earliest registered 
    -- 'Spectator' account has successfully purchased tickets.

SELECT DISTINCT t.venue_city
FROM reservations r
JOIN tickets t ON r.ticket_id = t.ticket_id
WHERE r.user_id = (
    SELECT user_id 
    FROM users 
    WHERE role = 'Spectator'
    ORDER BY created_at ASC 
    LIMIT 1
)
AND r.reservation_status = 'Confirmed';

